# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\Calcular.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    styleSheetOkay = ("QLineEdit {\n"
                      "    border:2px solid rgb(45, 45, 45);\n"
                      "    border-radius: 5px;\n"
                      "    padding: 15px;\n"
                      "    background-color: rgb(30, 30, 30);\n"
                      "    color: rgb(100, 100, 100);\n"
                      "}\n"
                      "QLineEdit:hover {\n"
                      "    border: 2px solid rgb(55, 55, 55);\n"
                      "}\n"
                      "QLineEdit:focus {\n"
                      "    border: 2px solid rgb(255, 207, 0);\n"
                      "    color: rgb(200, 200, 200,);\n"
                      "}")

    styleSheetError = ("QLineEdit {\n"
                       "    border:2px solid rgb(255, 114, 101);\n"
                       "    border-radius: 5px;\n"
                       "    padding: 15px;\n"
                       "    background-color: rgb(30, 30, 30);\n"
                       "    color: rgb(100, 100, 100);\n"
                       "}\n"
                       "QLineEdit:hover {\n"
                       "    border: 2px solid rgb(55, 55, 55);\n"
                       "}\n"
                       "QLineEdit:focus {\n"
                       "    border: 2px solid rgb(255, 207, 0);\n"
                       "    color: rgb(200, 200, 200,);\n"
                       "}")
    def checkCalculo(self):
        populacao = ""
        confianca = ""
        amostral = ""
        proporcao = ""
        
        #Check População
        if not self.total_populacao.text():
            self.total_populacao.setStyleSheet(self.styleSheetError)
        else:
            self.total_populacao.setStyleSheet(self.styleSheetOkay)
            populacao = self.total_populacao.text()
            n = int(populacao)

        #CHECK ERRO AMOSTRAL    
        if not self.error_amostral.text():
            self.error_amostral.setStyleSheet(self.styleSheetError)
        else:
            self.error_amostral.setStyleSheet(self.styleSheetOkay)
            amostral = self.error_amostral.text()
            e = float(amostral.replace(",", "."))
            
        
        #CHECK vERDADEIRA PROPORÇÃO
        if not self.estc_proporcao.text():
            p = 50.0
        else:
            self.estc_proporcao.setStyleSheet(self.styleSheetOkay)
            proporcao = self.estc_proporcao.text()
            p = float(proporcao.replace(",", "."))
        
        def showMessage(message):
                self.resultado.show()
                self.resultado.setText(message)

        #
        #Nível de Proporção
        #
        if ui.n_conf.currentText():
            conf = ui.n_conf.currentText()
            if conf == "90%":
                z = 1.65
            if conf == "95%":
                z = 1.96
            if conf == "95.5%":
                z = 2.0
            if conf == "99%":
                z= 2.57

        #
        #Calculo
        #
        if not self.error_amostral.text() or not self.total_populacao.text():
            msg = "ERRO"
            showMessage(msg)
        else:
            result = round((n * (z ** 2) * (p / 100) * (1 - (p / 100)))/((( e / 100) ** 2) *(n - 1) + (z ** 2) * (p / 100) * (1 - (p / 100))), 2)
            msg = str(result)
            showMessage(msg)    
                    


    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(953, 883)
        MainWindow.setMinimumSize(QtCore.QSize(488, 653))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalFrame = QtWidgets.QFrame(self.centralwidget)
        self.horizontalFrame.setStyleSheet("background-color: black;")
        self.horizontalFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.horizontalFrame)
        self.horizontalFrame_2.setMaximumSize(QtCore.QSize(450, 550))
        self.horizontalFrame_2.setStyleSheet("background-color: rgb(59, 59, 59);\n"
                                             "border-radius: 20px;\n"
                                             "color: white;")
        self.horizontalFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.calcular = QtWidgets.QPushButton(self.horizontalFrame_2)
        self.calcular.setGeometry(QtCore.QRect(140, 360, 150, 35))
        self.calcular.setStyleSheet("QPushButton{\n"
                                    "    background-color: rgb(50, 50, 50);\n"
                                    "    border: 2px solid rgb(60, 60, 60);\n"
                                    "    border-radius: 5px;\n"
                                    "}\n"
                                    "QPushButton:hover{\n"
                                    "    background-color: rgb(60, 60, 60);\n"
                                    "    border: 2px solid rgb(70, 70, 70);\n"
                                    "}\n"
                                    "QPushButton:pressed{\n"
                                    "    background-color: rgb(250, 230, 0);\n"
                                    "    border: 2px solid rgb(255, 165, 24);\n"
                                    "    color: rgb(35, 35, 35);\n"
                                    "}")
        self.calcular.setAutoDefault(False)
        self.calcular.setObjectName("calcular")
        self.total_populacao = QtWidgets.QLineEdit(self.horizontalFrame_2)
        self.total_populacao.setGeometry(QtCore.QRect(210, 100, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.total_populacao.setFont(font)
        self.total_populacao.setStyleSheet(self.styleSheetOkay)
        self.total_populacao.setText("")
        self.total_populacao.setMaxLength(1000000000)
        self.total_populacao.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.total_populacao.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.total_populacao.setObjectName("total_populacao")
        self.error_amostral = QtWidgets.QLineEdit(self.horizontalFrame_2)
        self.error_amostral.setGeometry(QtCore.QRect(210, 160, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.error_amostral.setFont(font)
        self.error_amostral.setStyleSheet(self.styleSheetOkay)
        self.error_amostral.setText("")
        self.error_amostral.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.error_amostral.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.error_amostral.setObjectName("error_amostral")
        self.n_conf = QtWidgets.QComboBox(self.horizontalFrame_2)
        self.n_conf.setGeometry(QtCore.QRect(250, 220, 70, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.n_conf.setFont(font)
        self.n_conf.setStyleSheet("QLineEdit {\n"
                                  "    border:2px solid rgb(45, 45, 45);\n"
                                  "    border-radius: 5px;\n"
                                  "    padding: 15px;\n"
                                  "    background-color: rgb(30, 30, 30);\n"
                                  "    color: rgb(100, 100, 100);\n"
                                  "}\n"
                                  "QLineEdit:hover {\n"
                                  "    border: 2px solid rgb(55, 55, 55);\n"
                                  "}\n"
                                  "QLineEdit:focus {\n"
                                  "    border: 2px solid rgb(255, 207, 0);\n"
                                  "    color: rgb(200, 200, 200,);\n"
                                  "}")
        self.n_conf.setObjectName("n_conf")
        self.estc_proporcao = QtWidgets.QLineEdit(self.horizontalFrame_2)
        self.estc_proporcao.setGeometry(QtCore.QRect(210, 270, 150, 50))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.estc_proporcao.setFont(font)
        self.estc_proporcao.setStyleSheet(self.styleSheetOkay)
        self.estc_proporcao.setText("")
        self.estc_proporcao.setEchoMode(QtWidgets.QLineEdit.Normal)
        self.estc_proporcao.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.estc_proporcao.setObjectName("estc_proporcao")
        self.plainTextEdit = QtWidgets.QPlainTextEdit(self.horizontalFrame_2)
        self.plainTextEdit.setGeometry(QtCore.QRect(96, 30, 271, 71))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(15)
        font.setBold(False)
        font.setWeight(50)
        self.plainTextEdit.setFont(font)
        self.plainTextEdit.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.plainTextEdit.setStyleSheet("color:white;")
        self.plainTextEdit.setObjectName("plainTextEdit")
        self.lcdNumber = QtWidgets.QLCDNumber(self.horizontalFrame_2)
        self.lcdNumber.setGeometry(QtCore.QRect(170, 430, 100, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lcdNumber.setFont(font)
        self.lcdNumber.setObjectName("lcdNumber")
        self.plainTextEdit_2 = QtWidgets.QPlainTextEdit(self.horizontalFrame_2)
        self.plainTextEdit_2.setGeometry(QtCore.QRect(170, 410, 104, 71))
        self.plainTextEdit_2.setObjectName("plainTextEdit_2")
        self.label_2 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_2.setGeometry(QtCore.QRect(122, 100, 100, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_3.setGeometry(QtCore.QRect(95, 160, 121, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_4.setGeometry(QtCore.QRect(60, 210, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_5.setGeometry(QtCore.QRect(40, 270, 181, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.box_result = QtWidgets.QFrame(self.horizontalFrame_2)
        self.box_result.setGeometry(QtCore.QRect(140, 460, 181, 47))
        self.box_result.setObjectName("box_result")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.box_result)
        self.verticalLayout_3.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.resultado = QtWidgets.QLabel(self.box_result)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.resultado.setFont(font)
        self.resultado.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.resultado.setAlignment(QtCore.Qt.AlignCenter)
        self.resultado.setObjectName("resultado")
        self.verticalLayout_3.addWidget(self.resultado)
        self.label_6 = QtWidgets.QLabel(self.horizontalFrame_2)
        self.label_6.setGeometry(QtCore.QRect(140, 410, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Myanmar Text")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: yellow;")
        self.label_6.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.label_2.raise_()
        self.calcular.raise_()
        self.total_populacao.raise_()
        self.error_amostral.raise_()
        self.n_conf.raise_()
        self.estc_proporcao.raise_()
        self.plainTextEdit.raise_()
        self.lcdNumber.raise_()
        self.plainTextEdit_2.raise_()
        self.box_result.raise_()
        self.label_6.raise_()
        self.horizontalLayout.addWidget(self.horizontalFrame_2)
        self.verticalLayout_2.addWidget(self.horizontalFrame)
        self.verticalFrame_2 = QtWidgets.QFrame(self.centralwidget)
        self.verticalFrame_2.setMaximumSize(QtCore.QSize(16777215, 35))
        self.verticalFrame_2.setStyleSheet(
            "background-color:rgb(255, 207, 0);")
        self.verticalFrame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.verticalFrame_2.setObjectName("verticalFrame_2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame_2)
        self.verticalLayout.setContentsMargins(9, 9, 9, 9)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.verticalFrame_2)
        self.label.setAlignment(
            QtCore.Qt.AlignRight | QtCore.Qt.AlignTrailing | QtCore.Qt.AlignVCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_2.addWidget(self.verticalFrame_2)
        MainWindow.setCentralWidget(self.centralwidget)

        # BT Conta
        self.calcular.clicked.connect(self.checkCalculo)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.n_conf.addItems(["90%","95%", "95.5%", "99%"])

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.calcular.setText(_translate("MainWindow", "Calcular"))
        self.total_populacao.setPlaceholderText(
            _translate("MainWindow", "1000"))
        self.error_amostral.setPlaceholderText(_translate("MainWindow", "0%"))
        self.estc_proporcao.setPlaceholderText(_translate("MainWindow", "0%"))
        self.plainTextEdit.setPlainText(_translate(
            "MainWindow", "Calculadora De Amostragem"))
        self.label_2.setText(_translate("MainWindow", "População:"))
        self.label_3.setText(_translate("MainWindow", "Erro Amostral:"))
        self.label_4.setText(_translate("MainWindow", "Nível De Confiança:"))
        self.label_5.setText(_translate("MainWindow", "Verdadeira Proporção:"))
        self.resultado.setText(_translate("MainWindow", "0"))
        self.label_6.setText(_translate("MainWindow", "Tamnha Da Amostra"))
        self.label.setText(_translate(
            "MainWindow", "Created by: Marcos Rangel R. Zanoni"))
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
